const SITE_BASE = location.pathname.startsWith('/vision/') ? '/vision/' : '/';
const isGithub = location.hostname.endsWith('github.io');
const siteUrl = (path) => SITE_BASE + String(path).replace(/^\/+/, '');
const profileUrl = (slug) => isGithub ? siteUrl(`business.html?slug=${encodeURIComponent(slug)}`) : siteUrl(`business/${encodeURIComponent(slug)}`);
const demo = [
 {id:'demo-1',slug:'himalayan-trails-tours',name:'Himalayan Trails & Tours',category:'Tour Operator',city:'Gangtok',state:'Sikkim',verified:true,rating:4.9,reviewCount:86,about:'Sikkim tour packages, transfers, sightseeing and trekking with local trip support.',phone:'+91 98765 43210',cover_image:'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=85'},
 {id:'demo-2',slug:'mountain-mist-homestay',name:'Mountain Mist Homestay',category:'Homestay',city:'Pelling',state:'Sikkim',verified:true,rating:4.8,reviewCount:52,about:'Comfortable mountain rooms, local food and sightseeing support.',phone:'+91 98765 10020',cover_image:'https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=1200&q=85'},
 {id:'demo-3',slug:'summit-cab-sikkim',name:'Summit Cab Sikkim',category:'Taxi',city:'Gangtok',state:'Sikkim',verified:true,rating:4.7,reviewCount:114,about:'Airport transfers and sightseeing cabs between Bagdogra, NJP and Sikkim.',phone:'+91 98765 33440',cover_image:'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=85'},
 {id:'demo-4',slug:'cloudline-adventures',name:'Cloudline Adventures',category:'Adventure',city:'Darjeeling',state:'West Bengal',verified:true,rating:4.9,reviewCount:43,about:'Trekking, camping and locally guided outdoor experiences.',phone:'+91 98765 92010',cover_image:'https://images.unsplash.com/photo-1551632811-561732d1e306?auto=format&fit=crop&w=1200&q=85'},
 {id:'demo-5',slug:'roots-of-the-hills',name:'Roots of the Hills',category:'Guide',city:'Manali',state:'Himachal Pradesh',verified:false,rating:4.6,reviewCount:31,about:'Local guides for culture walks, village experiences and mountain trails.',phone:'+91 98765 22331',cover_image:'https://images.unsplash.com/photo-1464278533981-50106e6176b1?auto=format&fit=crop&w=1200&q=85'},
 {id:'demo-6',slug:'lakeview-retreat',name:'Lakeview Retreat',category:'Hotel',city:'Udaipur',state:'Rajasthan',verified:true,rating:4.6,reviewCount:78,about:'Comfortable rooms, breakfast, pool access and local sightseeing support.',phone:'+91 98765 44112',cover_image:'https://images.unsplash.com/photo-1564501049412-61c2a3083791?auto=format&fit=crop&w=1200&q=85'}
];
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function card(b){const u=profileUrl(b.slug);const wa=(b.whatsapp||b.phone||'').replace(/\D/g,'');return `<article class="biz-card"><a class="biz-photo-link" href="${u}"><div class="biz-image" style="background-image:url('${esc(b.cover_image||'')}')"></div></a><div class="biz-body"><div class="biz-kicker"><span>${esc(b.category||'Travel business')} · ${esc(b.city||'')}</span>${b.verified?'<span class="verified">✓ Verified</span>':''}</div><h3><a href="${u}">${esc(b.name)}</a></h3><p>${esc(b.about||'')}</p><div class="biz-meta"><span class="rating-pill">${b.rating?'★ '+b.rating:'New'} <span class="review-count">${b.reviewCount?`(${b.reviewCount})`:''}</span></span><span class="listing-status">${b.verified?'Verified listing':'Published'}</span></div><div class="biz-actions"><a class="btn btn-primary btn-sm" href="tel:${esc(b.phone||'')}">Call</a><a class="btn btn-light btn-sm" href="${u}">View details</a>${wa?`<a class="btn btn-light btn-sm" href="https://wa.me/${wa}">WhatsApp</a>`:''}</div></div></article>`}
async function loadBusinesses(params=''){try{const r=await fetch(siteUrl('api/businesses')+params);if(!r.ok)throw new Error('api');return (await r.json()).items||[]}catch{return demo}}
async function home(){const el=document.getElementById('featuredBusinesses');if(!el)return;el.innerHTML=(await loadBusinesses('')).slice(0,6).map(card).join('');const y=document.getElementById('year');if(y)y.textContent=new Date().getFullYear()}
async function explore(){const results=document.getElementById('results');if(!results)return;const p=new URLSearchParams(location.search);const qEl=document.getElementById('q'),catEl=document.getElementById('category'),cityEl=document.getElementById('city'),verifiedEl=document.getElementById('verified'),sortEl=document.getElementById('sort'),form=document.getElementById('searchForm'),clearEl=document.getElementById('clear');if(!qEl)return;qEl.value=p.get('q')||'';catEl.value=p.get('category')||'';cityEl.value=p.get('city')||'';async function render(){let qs=new URLSearchParams();if(qEl.value)qs.set('q',qEl.value);if(catEl.value)qs.set('category',catEl.value);if(cityEl.value)qs.set('city',cityEl.value);let items=await loadBusinesses(qs.toString()?`?${qs}`:'');if(verifiedEl.checked)items=items.filter(x=>x.verified);if(sortEl.value==='rating')items.sort((a,b)=>(b.rating||0)-(a.rating||0));if(sortEl.value==='reviews')items.sort((a,b)=>(b.reviewCount||0)-(a.reviewCount||0));document.getElementById('resultTitle').textContent=`${items.length} business${items.length===1?'':'es'} found`;results.innerHTML=items.length?items.map(card).join(''):'<div class="dashboard-panel"><h3>No matching businesses</h3><p>Try another destination, category or business name.</p></div>'}form.onsubmit=e=>{e.preventDefault();const qs=new URLSearchParams({q:qEl.value,category:catEl.value,city:cityEl.value});history.replaceState(null,'',`${siteUrl('explore.html')}?${qs}`);render()};clearEl.onclick=()=>{qEl.value=catEl.value=cityEl.value='';verifiedEl.checked=false;sortEl.value='new';history.replaceState(null,'',siteUrl('explore.html'));render()};[qEl,catEl,cityEl,verifiedEl,sortEl].forEach(x=>x.addEventListener('change',render));render()}
window.TripNest={SITE_BASE,isGithub,siteUrl,profileUrl,demo,esc};
home();explore();
