const SITE_BASE = location.pathname.startsWith('/vision/') ? '/vision/' : '/';
const isGithub = location.hostname.endsWith('github.io');
const siteUrl = (path) => SITE_BASE + String(path).replace(/^\/+/, '');
const profileUrl = (slug) => isGithub ? siteUrl(`business.html?slug=${encodeURIComponent(slug)}`) : siteUrl(`business/${encodeURIComponent(slug)}`);

/*
 * Real public businesses are listed here as directory examples.
 * We do not imply that these businesses have subscribed to TripNest.
 * Ratings/contact facts are based on public sources linked in each record.
 * Photos are taken from the businesses' own/publicly listed web properties where a direct image URL is available.
 * A listing without a confirmed image intentionally uses no fake/stock photo.
 */
const demo = [
 {id:'real-sawaaden',slug:'sawaaden-tours-and-travels',name:'Sawaaden Tours and Travels (Silk Route Tourism)',category:'Tour Operator',city:'Gangtok',state:'Sikkim',verified:false,rating:4.7,reviewCount:160,about:'Gangtok-based tour operator offering Sikkim sightseeing, Silk Route trips, homestays, cab services and hotel bookings.',phone:'+91977552239',whatsapp:'+91977552239',website:'https://sawaadentours.in/',address:'Near Titanic Park, MG Road, Gangtok, Sikkim 737101',hours:'Daily · contact business for current hours',cover_image:'',sourceLabel:'Public business information',sourceUrl:'https://www.justdial.com/Gangtok/Sawaaden-Tours-and-Travels-Mg-Marg-Near-Titanic-Park-Gangtok-Bazar/9999P3592-3592-180303155155-Z5T6_BZDET'},
 {id:'real-khangri',slug:'khangri-tours-treks',name:'Khangri Tours, Treks & Expeditions',category:'Adventure',city:'Gangtok',state:'Sikkim',verified:false,rating:null,reviewCount:0,about:'Sikkim-based Himalayan adventure operator founded in 1994, offering treks, tours and expeditions across Sikkim and the Eastern Himalayas.',phone:'+918116762251',whatsapp:'+918116762251',website:'https://khangrii.com/',address:'Khangri Building, Behind Axis Bank, M.G. Marg, Gangtok, Sikkim 737101',hours:'Contact business for current hours',cover_image:'https://khangrii.com/SliderImage/image?sliderImageId=2',sourceLabel:'Official website',sourceUrl:'https://khangrii.com/'},
 {id:'real-footprint',slug:'footprint-holidays',name:'Footprint Holidays',category:'Tour Operator',city:'Gangtok',state:'Sikkim',verified:false,rating:null,reviewCount:0,about:'Himalayan travel company offering Sikkim, Darjeeling and Bhutan tours, with packages, transport and local trip support.',phone:'+919593888555',whatsapp:'+919593888555',website:'https://www.footprintholiday.com/',address:'Gangtok, Sikkim',hours:'Contact business for current hours',cover_image:'https://www.footprintholiday.com/uploads/web_package/iStock-2233575052.jpg',sourceLabel:'Official website',sourceUrl:'https://www.footprintholiday.com/'},
 {id:'real-nbt',slug:'north-bengal-tourism',name:'North Bengal Tourism',category:'Travel Agency',city:'Siliguri',state:'West Bengal',verified:false,rating:4.5,reviewCount:668,about:'Domestic tour operator and travel agency serving Darjeeling, Sikkim, Dooars, Kalimpong, Bhutan and wider destinations.',phone:'+918145584286',whatsapp:'+918145584286',website:'https://explorenorthbengal.com/',address:'Siliguri, West Bengal, India',hours:'Contact business for current hours',cover_image:'https://explorenorthbengal.com/images/places/hero_darjeeling.webp',sourceLabel:'Official website',sourceUrl:'https://explorenorthbengal.com/'},
 {id:'real-travelzone',slug:'travelzone-tours-and-travels',name:'Travelzone Tours and Travels',category:'Tour Operator',city:'Gangtok',state:'Sikkim',verified:false,rating:null,reviewCount:0,about:'Tour operator established in 1996 offering customized and planned travel across Sikkim, Darjeeling, Northeast India, Nepal and Bhutan.',phone:'+919832013211',whatsapp:'+919832013211',website:'https://www.sikkimtravelzone.com/',address:'Church Road, Below Police Headquarters, Arithang, Gangtok, Sikkim 737101',hours:'Contact business for current hours',cover_image:'',sourceLabel:'Official website',sourceUrl:'https://www.sikkimtravelzone.com/about-us'},
 {id:'real-maahi',slug:'maahi-holidays-events',name:'Maahi Holidays & Events',category:'Travel Agency',city:'Siliguri',state:'West Bengal',verified:false,rating:4.8,reviewCount:0,about:'Siliguri-based travel agency offering holiday packages, hotels, car rentals, ticketing, visa and travel support.',phone:'+919933003346',whatsapp:'+919933003346',website:'https://www.maahiholidays.com/',address:'Siliguri, West Bengal, India',hours:'Contact business for current hours',cover_image:'',sourceLabel:'Official website',sourceUrl:'https://www.maahiholidays.com/'},
 {id:'real-twm',slug:'travel-with-me-holiday',name:'Travel With Me Holiday',category:'Tour Operator',city:'Darjeeling',state:'West Bengal',verified:false,rating:null,reviewCount:0,about:'Tour operator serving Darjeeling, Sikkim, Dooars, Bhutan, Assam, Meghalaya and nearby destinations with customized trips.',phone:'+919933003346',whatsapp:'+919933003346',website:'https://www.travelwithmeholiday.com/',address:'Darjeeling, West Bengal, India',hours:'Contact business for current hours',cover_image:'',sourceLabel:'Official website',sourceUrl:'https://www.travelwithmeholiday.com/'},
 {id:'real-eastern-meadows',slug:'eastern-meadows-tours',name:'Eastern Meadows Tours',category:'Tour Operator',city:'Siliguri',state:'West Bengal',verified:false,rating:null,reviewCount:0,about:'Siliguri travel operator offering customized solo, family, group, adventure and professional trips across the Himalayas and beyond.',phone:'+919434060380',whatsapp:'+919434060380',website:'https://www.easternmeadowstours.com/',address:'Siliguri, West Bengal, India',hours:'Contact business for current hours',cover_image:'',sourceLabel:'Official website',sourceUrl:'https://www.easternmeadowstours.com/'}
];

function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function fallbackAvatar(b){return `<div class="biz-image biz-image-empty"><div><span>TN</span><small>Photo not supplied</small></div></div>`}
function photo(b){return b.cover_image?`<div class="biz-image" style="background-image:url('${esc(b.cover_image)}')"></div>`:fallbackAvatar(b)}
function card(b){const u=profileUrl(b.slug);const wa=(b.whatsapp||b.phone||'').replace(/\D/g,'');const rating=b.rating?`★ ${b.rating}`:'No rating yet';const reviews=b.reviewCount?`(${b.reviewCount})`:'';return `<article class="biz-card"><a class="biz-photo-link" href="${u}">${photo(b)}</a><div class="biz-body"><div class="biz-kicker"><span>${esc(b.category||'Travel business')} · ${esc([b.city,b.state].filter(Boolean).join(', '))}</span>${b.verified?'<span class="verified">✓ Verified</span>':'<span class="listing-status">Public listing</span>'}</div><h3><a href="${u}">${esc(b.name)}</a></h3><p>${esc(b.about||'')}</p><div class="biz-meta"><span class="rating-pill">${rating} <span class="review-count">${reviews}</span></span><a class="source-link" href="${esc(b.sourceUrl||b.website||'#')}" target="_blank" rel="noopener">Source ↗</a></div><div class="biz-actions"><a class="btn btn-primary btn-sm" href="tel:${esc(b.phone||'')}">Call</a><a class="btn btn-light btn-sm" href="${u}">View details</a>${wa?`<a class="btn btn-light btn-sm" href="https://wa.me/${wa}">WhatsApp</a>`:''}</div></div></article>`}
async function loadBusinesses(params=''){try{const r=await fetch(siteUrl('api/businesses')+params);if(!r.ok)throw new Error('api');const items=(await r.json()).items||[];return items.length?items:demo}catch{return demo}}
async function home(){const el=document.getElementById('featuredBusinesses');if(!el)return;el.innerHTML=(await loadBusinesses('')).slice(0,6).map(card).join('');const y=document.getElementById('year');if(y)y.textContent=new Date().getFullYear()}
async function explore(){const results=document.getElementById('results');if(!results)return;const p=new URLSearchParams(location.search);const qEl=document.getElementById('q'),catEl=document.getElementById('category'),cityEl=document.getElementById('city'),verifiedEl=document.getElementById('verified'),sortEl=document.getElementById('sort'),form=document.getElementById('searchForm'),clearEl=document.getElementById('clear');if(!qEl)return;qEl.value=p.get('q')||'';catEl.value=p.get('category')||'';cityEl.value=p.get('city')||'';async function render(){let qs=new URLSearchParams();if(qEl.value)qs.set('q',qEl.value);if(catEl.value)qs.set('category',catEl.value);if(cityEl.value)qs.set('city',cityEl.value);let items=await loadBusinesses(qs.toString()?`?${qs}`:'');if(verifiedEl.checked)items=items.filter(x=>x.verified);if(sortEl.value==='rating')items.sort((a,b)=>(b.rating||0)-(a.rating||0));if(sortEl.value==='reviews')items.sort((a,b)=>(b.reviewCount||0)-(a.reviewCount||0));document.getElementById('resultTitle').textContent=`${items.length} business${items.length===1?'':'es'} found`;results.innerHTML=items.length?items.map(card).join(''):'<div class="dashboard-panel"><h3>No matching businesses</h3><p>Try another destination, category or business name.</p></div>'}form.onsubmit=e=>{e.preventDefault();const qs=new URLSearchParams({q:qEl.value,category:catEl.value,city:cityEl.value});history.replaceState(null,'',`${siteUrl('explore.html')}?${qs}`);render()};clearEl.onclick=()=>{qEl.value=catEl.value=cityEl.value='';verifiedEl.checked=false;sortEl.value='new';history.replaceState(null,'',siteUrl('explore.html'));render()};[qEl,catEl,cityEl,verifiedEl,sortEl].forEach(x=>x.addEventListener('change',render));render()}
window.TripNest={SITE_BASE,isGithub,siteUrl,profileUrl,demo,esc};
home();explore();