const SITE_BASE=location.pathname.startsWith('/vision/')?'/vision/':'/';const isGithub=location.hostname.endsWith('github.io');const siteUrl=p=>SITE_BASE+p.replace(/^\//,'');let sb,user,biz;
async function init(){let c;try{c=await fetch(siteUrl('api/config')).then(r=>r.ok?r.json():Promise.reject())}catch{c={supabaseUrl:'',supabaseAnonKey:''}}if(!c.supabaseUrl||!c.supabaseAnonKey){document.body.insertAdjacentHTML('afterbegin','<div class="announcement">⚙️ Live owner functions require the Vercel + Supabase deployment.</div>');return}sb=supabase.createClient(c.supabaseUrl,c.supabaseAnonKey);const s=await sb.auth.getSession();user=s.data.session?.user;if(!user){location.href=siteUrl('login.html');return}logout.onclick=()=>sb.auth.signOut().then(()=>location.href=siteUrl('login.html'));tabs();await loadBusiness()}
function tabs(){document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.dashboard-panel').forEach(x=>x.classList.add('hidden'));t.classList.add('active');document.getElementById('panel-'+t.dataset.tab).classList.remove('hidden');if(t.dataset.tab==='photos')loadPhotos();if(t.dataset.tab==='leads')loadLeads();if(t.dataset.tab==='reviewsPanel')loadReviews();if(t.dataset.tab==='preview'&&biz)previewFrame.src=isGithub?siteUrl(`business.html?slug=${encodeURIComponent(biz.slug)}`):siteUrl(`business/${encodeURIComponent(biz.slug)}`)})}
async function loadBusiness(){const r=await sb.from('businesses').select('*').eq('owner_id',user.id).maybeSingle();biz=r.data;if(!biz){const slug=`${(user.user_metadata?.full_name||'my-business').toLowerCase().replace(/[^a-z0-9]+/g,'-')}-${user.id.slice(0,6)}`;const created=await sb.from('businesses').insert({owner_id:user.id,slug,name:user.user_metadata?.full_name||'My Travel Business',category:'Tour Operator',subscription_status:'inactive',published:false}).select().single();biz=created.data}fill();loadStats();loadPhotos();}
function fill(){for(const [id,v] of Object.entries({name:biz.name,category:biz.category,city:biz.city,state:biz.state,phone:biz.phone,whatsapp:biz.whatsapp,website:biz.website,email:biz.email,address:biz.address,services:(biz.services||[]).join(', '),about:biz.about,hours:JSON.stringify(biz.opening_hours||{},null,2)})){const e=document.getElementById(id);if(e)e.value=v||''}substatus.textContent=biz.subscription_status||'Inactive';publicLink.href=isGithub?siteUrl(`business.html?slug=${encodeURIComponent(biz.slug)}`):siteUrl(`business/${encodeURIComponent(biz.slug)}`);profileForm.onsubmit=save}
async function save(e){e.preventDefault();saveMsg.textContent='Saving…';let hours={};try{hours=JSON.parse(document.getElementById('hours').value||'{}')}catch{return saveMsg.textContent='Opening hours must be valid JSON.'}const patch={name:name.value,category:category.value,city:city.value,state:state.value,phone:phone.value,whatsapp:whatsapp.value,website:website.value,email:email.value,address:address.value,services:services.value.split(',').map(x=>x.trim()).filter(Boolean),about:about.value,opening_hours:hours,updated_at:new Date().toISOString()};const r=await sb.from('businesses').update(patch).eq('id',biz.id).eq('owner_id',user.id).select().single();if(r.error){saveMsg.textContent=r.error.message;return}biz={...biz,...r.data};saveMsg.textContent='Saved ✓';publicLink.href=isGithub?siteUrl(`business.html?slug=${encodeURIComponent(biz.slug)}`):siteUrl(`business/${encodeURIComponent(biz.slug)}`)}
async function loadStats(){const [{count:rv},{count:ld}]=await Promise.all([sb.from('reviews').select('*',{count:'exact',head:true}).eq('business_id',biz.id),sb.from('enquiries').select('*',{count:'exact',head:true}).eq('business_id',biz.id)]);views.textContent=biz.views||0;reviews.textContent=rv||0;leads.textContent=ld||0}
async function loadPhotos(){const {data}=await sb.from('business_photos').select('*').eq('business_id',biz.id).order('sort_order');photoGrid.innerHTML=(data||[]).map(p=>`<div class="photo-item"><img src="${p.url}" alt="${esc(p.caption||biz.name)}"><button type="button" onclick="removePhoto('${p.id}')">×</button></div>`).join('')||'<p class="note">No photos yet.</p>'}
photoInput.onchange=async e=>{for(const file of [...e.target.files]){const path=`${user.id}/${biz.id}/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'-')}`;const up=await sb.storage.from('business-media').upload(path,file,{upsert:false});if(up.error)continue;const {data:{publicUrl}}=sb.storage.from('business-media').getPublicUrl(path);await sb.from('business_photos').insert({business_id:biz.id,owner_id:user.id,url:publicUrl,caption:file.name,sort_order:Date.now()})}await loadPhotos()}
async function removePhoto(id){const {data:p}=await sb.from('business_photos').select('url').eq('id',id).single();await sb.from('business_photos').delete().eq('id',id);if(p?.url){const marker='/business-media/';const ix=p.url.indexOf(marker);if(ix>=0)await sb.storage.from('business-media').remove([p.url.slice(ix+marker.length)])}loadPhotos()}
async function loadLeads(){const {data}=await sb.from('enquiries').select('*').eq('business_id',biz.id).order('created_at',{ascending:false});leadList.innerHTML=(data||[]).map(x=>`<div class="list-row"><strong>${esc(x.name)} · ${esc(x.phone||'')}</strong><small>${new Date(x.created_at).toLocaleString('en-IN')} · ${esc(x.status)}</small><p>${esc(x.message)}</p></div>`).join('')||'<p class="note">No enquiries yet.</p>'}
async function loadReviews(){const {data}=await sb.from('reviews').select('*').eq('business_id',biz.id).order('created_at',{ascending:false});reviewList.innerHTML=(data||[]).map(x=>`<div class="list-row"><strong>${esc(x.author_name)} · ${'★'.repeat(x.rating)}${'☆'.repeat(5-x.rating)}</strong><small>${new Date(x.created_at).toLocaleDateString('en-IN')}</small><p><b>${esc(x.title||'')}</b> ${esc(x.body)}</p></div>`).join('')||'<p class="note">No reviews yet.</p>';sb.channel(`reviews-${biz.id}`).on('postgres_changes',{event:'*',schema:'public',table:'reviews',filter:`business_id=eq.${biz.id}`},loadReviews).subscribe()}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
init();
