async function getConfig(){if(window.__cfg)return window.__cfg;window.__cfg=await fetch('/api/config').then(r=>r.json());return window.__cfg}
const demo=[
 {id:'demo-1',slug:'himalayan-trails-tours',name:'Himalayan Trails & Tours',category:'Tour Operator',city:'Gangtok',state:'Sikkim',verified:true,rating:4.9,reviewCount:86,about:'Sikkim tour packages, transfers, sightseeing and trekking with local trip support.',cover_image:'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=900&q=80'},
 {id:'demo-2',slug:'mountain-mist-homestay',name:'Mountain Mist Homestay',category:'Homestay',city:'Pelling',state:'Sikkim',verified:true,rating:4.8,reviewCount:52,about:'Comfortable mountain rooms, local food and sightseeing support.',cover_image:'https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=900&q=80'},
 {id:'demo-3',slug:'summit-cab-sikkim',name:'Summit Cab Sikkim',category:'Taxi',city:'Gangtok',state:'Sikkim',verified:true,rating:4.7,reviewCount:114,about:'Airport transfers and sightseeing cabs between Bagdogra, NJP and Sikkim.',cover_image:'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=900&q=80'}
];
function card(b){return `<article class="biz-card"><a href="/business/${encodeURIComponent(b.slug)}"><div class="biz-image" style="background-image:url('${b.cover_image||''}')"></div></a><div class="biz-body"><div class="biz-kicker"><span>${b.category} · ${b.city||''}</span>${b.verified?'<span class="verified">✓ Verified</span>':''}</div><h3><a href="/business/${encodeURIComponent(b.slug)}">${esc(b.name)}</a></h3><p>${esc(b.about||'')}</p><div class="biz-bottom"><span class="rating-pill">${b.rating?'★ '+b.rating:'New'} <span style="font-weight:500;color:#829087">${b.reviewCount?`(${b.reviewCount})`:''}</span></span><a class="biz-link" href="/business/${encodeURIComponent(b.slug)}">View profile →</a></div></div></article>`}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function loadBusinesses(params=''){try{const r=await fetch('/api/businesses'+params);if(!r.ok)throw 0;return (await r.json()).items||[]}catch{return demo}}
async function home(){const el=document.getElementById('featuredBusinesses');if(!el)return;el.innerHTML=(await loadBusinesses('')).slice(0,6).map(card).join('')||demo.map(card).join('')}
async function explore(){const results=document.getElementById('results');if(!results)return;const p=new URLSearchParams(location.search);q.value=p.get('q')||'';category.value=p.get('category')||'';city.value=p.get('city')||'';async function render(){let qs=new URLSearchParams();if(q.value)qs.set('q',q.value);if(category.value)qs.set('category',category.value);if(city.value)qs.set('city',city.value);let items=await loadBusinesses(qs.toString()?`?${qs}`:'');if(document.getElementById('verified').checked)items=items.filter(x=>x.verified);if(sort.value==='rating')items.sort((a,b)=>b.rating-a.rating);if(sort.value==='reviews')items.sort((a,b)=>b.reviewCount-a.reviewCount);document.getElementById('resultTitle').textContent=`${items.length} business${items.length===1?'':'es'} found`;results.innerHTML=items.length?items.map(card).join(''):'<div class="dashboard-panel"><h3>No matching businesses</h3><p>Try a broader search.</p></div>'}searchForm.onsubmit=e=>{e.preventDefault();history.replaceState(null,'',`/explore.html?${new URLSearchParams({q:q.value,category:category.value,city:city.value})}`);render()};clear.onclick=()=>{q.value=category.value=city.value='';verified.checked=false;sort.value='new';history.replaceState(null,'','/explore.html');render()};[q,category,city,verified,sort].forEach(x=>x.addEventListener('change',render));render()}
home();explore();
